region: ap-south-1
key_name: honorlaptop
instance_type: t2.micro
ami_id: ami-08e7318c2e031024c
vpc_id: vpc-0db825702939b11a0
subnet_id: subnet-06dba24b763624c5e
instance_name: dns-server

allowed_ssh_ip: 0.0.0.0/0   # 🔴 CHANGE THIS

domain_name: kbvsm.com

ansible_user: ec2-user
ansible_ssh_private_key_file: /root/honorlaptop.pem
