- name: Provision EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - ec2

- name: Refresh inventory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Refresh dynamic inventory
      meta: refresh_inventory

- name: Wait for EC2 SSH
  hosts: tag_dns
  gather_facts: no
  tasks:
    - name: Wait for SSH to become available
      wait_for_connection:
        delay: 10
        timeout: 300

- name: Configure DNS server
  hosts: tag_dns
  become: yes
  roles:
    - dns
