- name: Provision EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - ec2


# 🔴 Ensure instance is reachable before config
- name: Wait for EC2 SSH
  hosts: tag_dns
  gather_facts: no

  tasks:
    - name: Wait for SSH connection
      wait_for_connection:
        timeout: 300


- name: Configure DNS server
  hosts: tag_Role_dns
  become: yes
  gather_facts: yes

  roles:
    - dns
