- name: Install Bind
  yum:
    name: bind
    state: present

- name: Ensure /var/named exists
  file:
    path: /var/named
    state: directory
    owner: named
    group: named
    mode: '0755'

- name: Deploy named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart named

- name: Deploy zone file
  template:
    src: kbvsm.com.zone.j2
    dest: "/var/named/{{ domain_name }}.zone"
    owner: named
    group: named
    mode: '0644'
  notify: restart named

- name: Validate named.conf
  command: named-checkconf
  changed_when: false

- name: Validate zone file
  command: "named-checkzone {{ domain_name }} /var/named/{{ domain_name }}.zone"
  changed_when: false

- name: Ensure named is running
  service:
    name: named
    state: started
    enabled: yes
