- name: Install Bind
  yum:
    name: bind
    state: present

- name: Deploy named.conf
  copy:
    src: named.conf
    dest: /etc/named.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure /var/named directory exists
  file:
    path: /var/named
    state: directory
    owner: named
    group: named
    mode: '0755'

- name: Deploy zone file
  template:
    src: kbvsm.com.zone.j2
    dest: "/var/named/{{ domain_name }}.zone"
    owner: named
    group: named
    mode: '0644'

- name: Restart named service
  service:
    name: named
    state: restarted
    enabled: yes
