- name: Provision EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - block:

        - name: Run EC2 role
          import_role:
            name: ec2

      rescue:

        - name: Fail safely
          debug:
            msg: "❌ EC2 provisioning failed"

        - fail:
            msg: "Stopping playbook due to failure"


- name: Configure DNS server
  hosts: dns
  become: yes
  gather_facts: yes

  roles:
    - dns
