- name: Create security group
  amazon.aws.ec2_security_group:
    name: dns-sg
    description: DNS Security Group
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    state: present
    rules:
      - proto: tcp
        ports: 22
        cidr_ip: "{{ allowed_ssh_ip }}"
      - proto: udp
        ports: 53
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports: 53
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: sg


- name: Launch EC2 instance
  amazon.aws.ec2_instance:
    name: "{{ instance_name }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ ami_id }}"
    key_name: "{{ key_name }}"
    subnet_id: "{{ subnet_id }}"
    region: "{{ region }}"

    security_groups:
      - "{{ sg.group_id }}"

    network:
      assign_public_ip: true

    exact_count: 1
    
    ec2_tags:
      Name: "{{ instance_name }}"
      Role: dns
      Environment: dev

    wait: yes
  register: ec2


- name: Show instance info
  debug:
    msg: |
      EC2 instance launched!
      Public IP: {{ ec2.instances[0].public_ip_address | default('N/A') }}
      Private IP: {{ ec2.instances[0].private_ip_address | default('N/A') }}
